### ISSUE TITLE
Interstitial problem in production

### ISSUE THREAD

**Issue by morangoplanet** [sbugert/react-native-admob#116]
Hi all!

I have just integrated this react-native-admob component in my React Native project and I have no problem in the EMULATOR device. I can view my interstitial example ad that says I integrated the ad well.

When I create app release and I install it in my real android device, the app crashes when this interstitial ad must appear.

I am getting crazy and I don't know what to do. My project was done with React Native 0.24 version, and I thought this was the issue, but I updated to React Native 0.36 and the app is still crashing in the same point.

Do you have any idea? What should I do?

Thank you in advance!

**Comment by thiensubs** [comment]
Maybe same as me:
My error from Play Store:
`com.facebook.react.bridge.NativeArgumentsParseException: TypeError: expected dynamic type `double', but had type `string' (constructing arguments for RNAdMobInterstitial.showAd at argument index 0)`

**Comment by ricardofavero** [comment]
`com.facebook.react.bridge.NativeArgumentsParseException: TypeError: expected dynamic type double', but had typestring' (constructing arguments for RNAdMobInterstitial.showAd at argument index 0)`

I was getting this error because my ads had recently been created in AdMob. Just wait a few minutes or hours and they will start to appear normally.
Another possibility is that you're providing a wrong unitID.

**Comment by koenpunt** [comment]
This is probably because the README mentions a bit flaky usage example.

You should use it like:

```js
AdMobInterstitial.requestAd(() => AdMobInterstitial.showAd());
```

Instead of:

```js
AdMobInterstitial.requestAd(AdMobInterstitial.showAd);
```
