### ISSUE TITLE
Is this package still maintained ?

### ISSUE THREAD

**Issue by deadcoder0904** [sbugert/react-native-admob#186]
There are some [PRs](https://github.com/sbugert/react-native-admob/pulls) that are done & can be merged completely. They are small PRs like #182. 

I use this package a lot & I am sure many others too. So it is my humble request, @sbugert to add more maintainers who can actively maintain this project. 

Thank you for creating this package but if u don't have enough time plz add more maintainers so that others using it can benefit from it.

**Comment by koenpunt** [comment]
It is, v2 of the library is currently being developed. You can track its development here: https://github.com/sbugert/react-native-admob/pull/165. I use the alpha version in 2 app with both more than 10k users without issues, so I'd recommend you to check it out. The main reason it's still alpha is because I'm not completely happy with the current API, so method- and event names might still change before release. If you have any ideas or suggestions, please leave them as comments on that PR.

Nb. To comment on your "small PR" remark, the `prop-types` library is not backwards compatible with older versions of React/React Native, so it's actually not a "small PR".

**Comment by deadcoder0904** [comment]
Yep thanks. It was an issue on my side. Also, the publish banner was working only sometimes. Sometimes the ad wouldn't load so I stopped using it. Rest is working fine. Thank u for ur hard work.
