### ISSUE TITLE
testDeviveID="EMULATOR"

### ISSUE THREAD

**Issue by jonigl** [sbugert/react-native-admob#27]
Hi!

First of all thank you for share this component! :)

I would like to know which values can be placed at this property, and how can I use it.

Thanks!

**Comment by sbugert** [comment]
From the AdMob docs:

[Android](https://firebase.google.com/docs/admob/android/targeting#prerequisites)
> Remember to add a test device ID for each device that should request test ads. Device IDs are written to the system log by the Mobile Ads SDK, so you can find your device's ID by running your app and checking logcat.
> 
> The Mobile Ads SDK uses the tag "Ads" when writing to logcat. You can filter for that tag in Android Studio's logcat viewer, which makes it easier to find your device's ID.

[iOS](https://firebase.google.com/docs/admob/ios/targeting#test_ads)
> For devices, check the logs in Xcode when running your app and making an ad request. You'll get a log that looks like this:
> 
> <Google> To get test ads on this device, call: request.testDevices = @[
> @"2077ef9a63d2b398840261c8221a0c9b" ];

`'EMULATOR'` is special in this library because it maps to the corresponding constants on iOS (GAD_SIMULATOR_ID) and android (TEST_EMULATOR).
Hope that helps :)

**Comment by jonigl** [comment]
@sbugert thank you! This info really helps :)

Another question to clarify me about this parameter. If I want to submit my app to the App Store, I have to remove this parameter isn't it?

Thanks again!

**Comment by sbugert** [comment]
Yes, AdMob will only show test ads in test mode. I doubt you would want that in production :)

**Comment by jonigl** [comment]
Awesome @sbugert ! thanks! :)
