### ISSUE TITLE
ads not showing 

### ISSUE THREAD

**Issue by ssmlee04** [sbugert/react-native-admob#38]
I just registered an admob account and I tried to display a banner using `AdMobBanner` component. I can see that `didFailToReceiveAdWithError`is not called, also `adViewDidReceiveAd` is called and shows success but there is still nothing in the banner. 

So is there something that I do wrong?

**Comment by ssmlee04** [comment]
Also `AdMobInterstitial` will only popup a black screen with a close button but nothing else.

**Comment by sbugert** [comment]
Could you please try the google test id (also used in the [example project](https://github.com/sbugert/react-native-admob/tree/master/Example)) to rule out the possibility that the problem has something to do with your admob account?

**Comment by ssmlee04** [comment]
yes I used google's sample unit id `ca-app-pub-3940256099942544/2934735716` and it worked. So I guess that's just my account then.

**Comment by ssmlee04** [comment]
It appears that `AdMobBanner` is working and banner is showing up but `AdMobInterstitial` is not working. my RN is 0.28.0 and React is 15.2.1

**Comment by sbugert** [comment]
`No ad to show.` means that there is no ad for your admob id to show. Which id are you using?
`ca-app-pub-3940256099942544/1033173712` is the test id I'm using in the example project.

**Comment by ssmlee04** [comment]
I did something stupid. I used an Ad id that only serves banner. Guess that's why...

**Comment by melihberberolu** [comment]
@ssmlee04 Production mode my banner always return no ad to show. Can u help me ?

**Comment by Cawfree** [comment]
I've been struggling with this all day. Banners were rendering correctly on iOS (Simulator) but not Android. 

The fix that I was missing is that the `AndroidManifest.xml` must have an additional `intent` declaration:
````
<activity
  android:name="com.google.android.gms.ads.AdActivity"
  android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" />
````

Without this declaration, neither banners nor interstitials would load.

As a suggestion, it would be awesome if in the `README.md` for the repo you could state that the device id is printed in the console upon initialization of the app, and that the `simulatorId` only applies to emulators. But again, since I'm not too familiar with Admob, that is probably just me making a stupid mistake.

Many thanks for creating such a great library.
