### ISSUE TITLE
Working on react-native 0.13

### ISSUE THREAD

**Issue by sercanov** [sbugert/react-native-admob#4]
Actually tested it and managed to work out. What is the risk of not being work on 0.19 ? 

And when I try to use AdMobIntersititial.setAdUnitId method, I get 'undefined is not an object' error. 

Thanks

**Comment by sbugert** [comment]
First of all, are you referring to the iOS or android version?
The iOS version hasn't changed in a while so I see no problem in using it with 0.13 if it works.

For the android version I recently commited a fix because of a breaking change in how props are set in android custom ui components, hence the dependency on 0.19+.
So I assume you are on iOS which also explains the interstitial error. Apparently, I did not yet find the time to implement it on iOS. I should make that clear in the readme. 

Is there anything in particular preventing you from upgrading to the newest version?

**Comment by sercanov** [comment]
@sbugert Yes i was referring iOS version. I see the thing here, only problem is about interstitial so I will be waiting for it to implement. 

Thanks.
