### ISSUE TITLE
(Banner) Ads not showing/crashing in Release APK

### ISSUE THREAD

**Issue by JustGabeHere** [sbugert/react-native-admob#404]
Hello! I am having an issue with`AdMobBanner` in my release APK.
It appears that when I try to use a proper AdUnitID for my banner, nothing actually shows up. The banner Ad ID is valid, and everything still works fine.

I tried it with a test ID and it worked perfectly! But for some reason when I try to use a AdMob ID that is from my app, nothing shows up where it should be.

This could possibly be a connectivity issue, but my internet speed is just fine, and I tested the app multiple times.

(All of this happens in a release build, and not a debug build)

Hopefully there is a workaround/fix for this, because it has been bugging me for the past few hours.

**Comment by JustGabeHere** [comment]
Here is a code snippet. I've tried many solutions but still didn't work. 
And no, there isn't a red dot anywhere on the screen.

This is sandwiched in between a view, which makes it centred on the screen. 
`<AdMobBanner 
                    adSize="fullBanner" 
                    adUnitID="gabes-ad-unit-id" 
                    onAdFailedToLoad={error => console.error(error)} />`

**Comment by Momazo7u7** [comment]
The first time i used this library i was scared because none of my adds appeared. To my surprise it was due to my location, and the fact that i use microg instead of the native google play services... there was times when the ads showed up, but for other people using the app the ads were always there. 

That was for the first 2 weeks until everything was normal, now i see ads from time to time. If you see test ads then it's working, it0s using the same type of request for the test id than for the real id so don't worry, and be patient

**Comment by ursNj** [comment]
there are many reasons to get this error.

1. if you are testing with simulator, generally there are very limited ads to display, so we will get this error. but this will work in production.
2. If you have created your ad units newly, so that will take some time to become active for serving ads, generally it will take 3 - 5 days to get active, so please wait and have fun.
3. there will be some cases that you will keep some restrictions on serving ads like only display amount more than certain amount, that time ads may not be available for serving the same. so keep your ad settings always in an optimised manner.

i think these are the possible causes. let me know if you need any other info

**Comment by JustGabeHere** [comment]
Sorry for the informal close of the issue, the owners of the repo can probably delete this.

It has been a while since the issue has been opened, and I have changed to a different framework. Thanks for the help anyway!
