### ISSUE TITLE
Support Facebook and Mopub ads

### ISSUE THREAD

**Issue by vu-dang** [sbugert/react-native-admob#43]
This is not an issue but more of a feature request.  The library works great for admob. Would it be possible to support Mopub and Facebook banner ads too.

**Comment by th0th** [comment]
As far as I can remember, Mopub was available as a mediation network in Admob. If so, you can add Mopub as mediation network to your Admob account, add Mopub SDK to your app and you are ready to go.

But I don't know anything about Facebook banner ads and I tihkn that should be another library since this library is for Admob.
