### ISSUE TITLE
ERROR "framesToPop": 1 on android devices

### ISSUE THREAD

**Issue by HamoMinasyan** [sbugert/react-native-admob#430]
Ads are working fine on emulators but when I run apk on real devices it gives me the following error
<img width="330" alt="Screen Shot 2019-04-10 at 17 03 01" src="https://user-images.githubusercontent.com/16427511/55882076-effbac80-5bb4-11e9-86c1-30126cda0c24.png">

Versions.
    "react": "16.8.3",
    "react-native": "0.59.0"

Please give me a solution as soon as possible.
Thanks in advance

**Comment by niravpatel2111** [comment]
yes i got the same issue 
is there any way to fix this ?
please give us some solution 
Thanks

**Comment by koenpunt** [comment]
This error is probably coming from a `console.log` that lives in your codebase. The fact that it looks like an object is because the object gets extended with this `framesToPop` property here; https://github.com/sbugert/react-native-admob/blob/f8db0e6797efcda101e936e1bbe0c91d3f174a15/utils.js#L7 

But other than that it's just a serialized javascript error. Try looking in the device logs for the full error message. I expect it to be something like "ad not loaded".

**Comment by HamoMinasyan** [comment]
@koenpunt Thanks for your suggestion however that does not help. :(

**Comment by HamoMinasyan** [comment]
@niravpatel2111could you solve this error ?

**Comment by fernando-pascoal** [comment]
some problem with PublisherBanner for adManager, works on test banner but not in production
