### ISSUE TITLE
Application crashes on prod

### ISSUE THREAD

**Issue by RatFou** [sbugert/react-native-admob#51]
Hi,
This component seems to be really great, I managed to run it in emulator.  But when I use it on my phone (Android), it crashes when I click on the link to show the interstitial ad.
I tried to see what is the problem with logcat, but the error is not documented.

Have you some advice on that problem?

Thank you.

**Comment by RatFou** [comment]
I was searching the wrong word in catlog (my app name). After looking for "admob", catlog gave me those errors:
- undefined is not a function (evaluating 'u.AdMobInterstitial.setAdUnitID("ca-app-pub-[MYID]")')
- com.facebook.react.modules.core.Java scriptException: [same value as the first error], stack:

Any ideas?

**Comment by sbugert** [comment]
Can you show me your code?

I haven't come across this issue yet.

**Comment by RatFou** [comment]
Sure, you can download a project with just admob on it: https://drive.google.com/open?id=0B2-fvDtYwHQyNFptaXhtUDJwQVU

Thank you for your time.

**Comment by sbugert** [comment]
Sorry for the late reply!

```javascript
class AdMob extends Component {

  render() {
    AdMobInterstitial.setAdUnitID('ca-app-pub-8814644486029059/7718152351');
    AdMobInterstitial.setTestDeviceID('EMULATOR');
    AdMobInterstitial.requestAd(AdMobInterstitial.showAd);
    return (
      <View></View>
    )
  }

}
```

I'm not sure whether this is the real problem but you should not set the ad unit and test device in the render function. Since the interstitial module is a singleton you are good to move it outside of the component (assuming the values won't change during runtime).
Also, I don't think calling `requestAd` in render() is what you want. I guess you want to show an interstitial every time the navigator renders HomeScreen? If so, you should use the lifecycle hook `ComponentDidMount`.
Unfortunately, I don't have access to an android device right now so I can only test it in the emulator.

The code should look something like this:

```javascript
import React, { Component } from 'react'
import { AdMobInterstitial } from 'react-native-admob'

AdMobInterstitial.setAdUnitID('ca-app-pub-8814644486029059/7718152351')
AdMobInterstitial.setTestDeviceID('EMULATOR')

class AdMob extends Component {
  componentDidMount() {
    AdMobInterstitial.requestAd(AdMobInterstitial.showAd)
  }

  render() {
    return null
  }
}

module.exports = AdMob
```

(Btw you can return null if you don't want to render any components, there's no need for empty View components.)

In AppNavigator.js there's a typo in line 41. It should say `configueScene`.


In general, you could also improve the design by preloading the interstitial before showing the home screen a second time. This could be achieved by calling `requestAd` in the `interstitialDidClose` lifecycle event. This way there is no delay before showing it for the second time. The example project makes use of these hooks if you need a reference.

Hope that helps! Tell me if this was not the problem :)

**Comment by RatFou** [comment]
Hi!
Thank you for this code, it seems to be working on my Android phone now :)

I will try the `requestAd` in other screen.
