### ISSUE TITLE
The ad unit ID can only be set once on InterstitialAd

### ISSUE THREAD

**Issue by justfede** [sbugert/react-native-admob#79]
Hey guys! It's anyway to check if unit ID is already setted up to avoid this exception?

Thanks!

**Comment by mihaben** [comment]
I had the same problem, in my case I fixed the problem setting the IntersitialAd id just in index.android.js and index.ios.js

**Comment by marcusds** [comment]
@mihaben how did you go about doing that? I tried and it just causes the app to crash.

**Comment by fcpauldiaz** [comment]
I'm having the same error @mihaben from where did you removed it ?

**Comment by mihaben** [comment]
Hey @fcpauldiaz and @marcusds , I was setting the InterstitialAd inside a component, so.. every time that the component was rendered, the InterstitialAd was setting again and that was provoking the problem, to fix the problem I moved the next 2 lines:

```
AdMobInterstitial.setAdUnitID('ca-app-pub-you-id');
AdMobInterstitial.setTestDeviceID('EMULATOR');
```

to index.android.js and index.ios.js, in this way you are just setting the ads when the app is started.

And inside the component, the code to show the ad:

`AdMobInterstitial.requestAd(AdMobInterstitial.showAd); `

**Comment by emrecanozkok** [comment]
set to global variable top of the index.js
`var adIdSet = false; `

and when you show itiyou need to check and your first time you wil need to set.

`if (adIdSet != true) {
         AdMobInterstitial.setAdUnitID('ca-app-pub-2379123131358452/1851902925');
         AdMobInterstitial.setTestDeviceID('EMULATOR');
         AdMobInterstitial.requestAd(AdMobInterstitial.showAd);
         adIdSet = true;
}else{
        AdMobInterstitial.requestAd(AdMobInterstitial.showAd);
}
`

**Comment by justfede** [comment]
Hmm I still having this problem when the user minimize (android back button) the application and reopen it later...

**Comment by fcpauldiaz** [comment]
That must be because you open the interstitial on the onMount event, you have to move it before class declaration.






-------- Mensaje original --------
De: Federico Carrizo <notifications@github.com>
Fecha: 18/3/17 3:38 PM (GMT-06:00)
Para: sbugert/react-native-admob <react-native-admob@noreply.github.com>
Cc: Pablo Díaz Márquez <pablo5_diaz@hotmail.com>, Mention <mention@noreply.github.com>
Asunto: Re: [sbugert/react-native-admob] The ad unit ID can only be set once on InterstitialAd (#79)


Hmm I still having this problem when the user minimize (android back button) the application and reopen it later...

**Comment by Porshe** [comment]
I had the same problem on production.
Pull request #121 can fix this issue

**Comment by sachinwak** [comment]
moving it before class declaration work for me thanks @fcpauldiaz

**Comment by itchingpixels** [comment]
We're bumping into the same issue.
It seems like everywhere else (like rewarded video, banner module, etc), before setting the ad unit id, there's a check whether the ID has been already set or not, except for InterstitialAd.
Is this intentional?

![image](https://user-images.githubusercontent.com/5416288/32174377-90ca7122-bd79-11e7-814f-6a4fc27cd93c.png)

I think all of our problems would be solved if there was a check in RNAdMobInterstitialAdModule.java, too.

**Comment by itchingpixels** [comment]
There's a PR with a fix: https://github.com/sbugert/react-native-admob/pull/204 waiting to be merged
