### ISSUE TITLE
Change Background from black and align center.

### ISSUE THREAD

**Issue by renwaldo** [sbugert/react-native-admob#97]
Apologies if this is the wrong place - But how would I go about changing the banner ad background to inherit the app background colour instead of the default black colour. And making sure it aligns horizontally in the center app.

Any help hugely appreciated.

Cheers,
Renny.

**Comment by koenpunt** [comment]
I guess this isn't possible if the banner by default isn't transparent, since there's no way to set the style property of the actual banner component, only that of the wrapper view. However, in the next version of this library you can set the style property of the banner view, since there's no longer a wrapper view. You can check it out here: #165

**Comment by koenpunt** [comment]
Since v2 is now available as beta I'm going to close this.
